const pages = ['home','orakai','agents','lineage','evolutions','wiki','energy','settings'];
const labels = ['Home','Orakai','Agents','Lineage','Evolutions','Wikis','Energy','Settings'];
const icons = ['⌂','◉','☷','✣','✦','▣','⚡','⚙'];
const agentHtml = `
  <div class="agents">
    <article class="agent" style="--a:#9b7cff"><div class="art"><div class="sym">✦</div></div><div class="info"><h3>Kaien</h3><p><b>Life Strategist</b></p><p>Helps you make better decisions and plan ahead.</p><span class="pill">Active</span></div></article>
    <article class="agent" style="--a:#63b9ff"><div class="art"><div class="sym">♫</div></div><div class="info"><h3>Soraka</h3><p><b>Music Curator</b></p><p>Finds the perfect music for your mood and moments.</p><span class="pill">Active</span></div></article>
    <article class="agent" style="--a:#6ed69a"><div class="art"><div class="sym">♥</div></div><div class="info"><h3>Hinari</h3><p><b>Wellness Companion</b></p><p>Supports your well-being and daily balance.</p><span class="pill">Active</span></div></article>
    <article class="agent" style="--a:#f2b84b"><div class="art"><div class="sym">▥</div></div><div class="info"><h3>Zenro</h3><p><b>Finance Sage</b></p><p>Guides your finances and smart money moves.</p><span class="pill">Dormant</span></div></article>
  </div>`;
function list(title, rows){return '<section class="card pad"><div class="head"><h2>'+title+'</h2><button class="link">View all</button></div><div class="list">'+rows.map(r=>'<div class="li"><div class="ico">'+r[0]+'</div><div><b>'+r[1]+'</b><span>'+r[2]+'</span></div></div>').join('')+'</div></section>'}
const views = {
  home: '<div class="home grid"><div class="grid"><section class="hero"><div class="kicker">Good morning, Seeker</div><h1>What shall we explore today?</h1><p>Orakai helps you navigate Anvaya, choose the right agents, preserve knowledge, and conserve energy.</p><div class="prompt"><input placeholder="Ask Orakai anything..."><button class="primary">→</button></div><div class="chips"><button class="chip">Plan my day</button><button class="chip">Summarize updates</button><button class="chip">Brainstorm ideas</button></div></section><section><div class="head"><h2>Active Agents</h2><button class="link">View all</button></div>'+agentHtml+'</section><section><div class="head"><h2>Universe at a Glance</h2><button class="link">Open Universe Map</button></div><div class="stats"><div class="stat"><b>6</b><br><span class="muted">Origins</span></div><div class="stat"><b>7</b><br><span class="muted">Active Agents</span></div><div class="stat"><b>3</b><br><span class="muted">Dormant Agents</span></div><div class="stat"><b>12</b><br><span class="muted">Evolutions</span></div></div></section></div><aside class="sidegrid"><section class="card pad"><div class="head"><h2>Realm Energy</h2><span class="muted">ⓘ</span></div><div class="energy-main"><div class="ring"><span>⚡</span></div><div><div class="num">74%</div><div class="muted">740 / 1000 Energy</div></div></div><div class="note">Daily regeneration in 08:45:12</div><button class="full">View Energy Details</button></section>'+list('Upcoming', [['✦','Weekly Review with Orakai','In 2h'],['♫','Music discovery with Soraka','In 5h'],['♥','Mindful check-in with Hinari','Tomorrow']])+list('Evolution Suggestions', [['✣','Merge Suggestion','Kaien + Zenro'],['⌘','Split Suggestion','Soraka to Sorami + Soryn']])+'</aside></div>',
  orakai: '<div class="title"><div><h1>Orakai</h1><p>The Master Agent routes requests, chooses the minimum necessary agents, synthesizes answers, and preserves realm energy.</p></div><button class="primary">Premium Active</button></div><section class="card chat"><div class="chathead"><div class="orb">◉</div><div><b>Orakai - Keeper of Lineage</b><div class="muted">Master of routing and memory efficiency</div></div></div><div class="body"><div class="bubble user">Help me plan a focused evening. Keep it brief.</div><div class="bubble agent">I will consult only Kaien. Estimated cost: 5 energy.</div><div class="bubble agent">Plan: reset, deep-work block, simple dinner, short walk, wind-down playlist. Energy saved: 7.</div></div><div class="chatinput"><input placeholder="Ask Orakai..."><button class="primary">Send</button></div></section>',
  agents: '<div class="title"><div><h1>Agents</h1><p>Manage characters, roles, tools, memories, and canonical wiki profiles.</p></div><button class="primary">Create Agent</button></div>'+agentHtml,
  lineage: '<div class="title"><div><h1>Lineage Map</h1><p>A navigable universe showing origins, agents, splits, merges, and dormant entities.</p></div></div><section class="map"><div class="node origin" style="left:42%;top:40px"><b>Nythera</b><small>Mystery</small></div><div class="node origin" style="left:9%;top:190px"><b>Kaelith</b><small>Wisdom</small></div><div class="node origin" style="right:9%;top:190px"><b>Veylune</b><small>Creativity</small></div><div class="node origin" style="left:42%;bottom:55px"><b>Solaryn</b><small>Vitality</small></div><div class="node" style="left:18%;top:330px"><b>Kaien</b><small>Life Strategist</small></div><div class="node" style="right:18%;top:330px"><b>Soraka</b><small>Music Curator</small></div><div class="node" style="left:42%;top:240px"><b>Orakai</b><small>Keeper of Lineage</small></div></section>',
  evolutions: '<div class="title"><div><h1>Evolutions</h1><p>Review merge, split, archive, and evolution suggestions before applying them.</p></div><button class="primary">Generate Suggestions</button></div><div class="grid"><article class="evo"><div class="big">✣</div><div><h3>Merge Recommendation</h3><p>Kaien + Zenro to Kaizeth</p><p class="muted">High overlap in planning and long-term strategy.</p></div><button class="chip">Review</button></article><article class="evo"><div class="big">⌘</div><div><h3>Split Recommendation</h3><p>Soraka to Sorami + Soryn</p><p class="muted">Music and design work are becoming separate domains.</p></div><button class="chip">Review</button></article></div>',
  wiki: '<div class="title"><div><h1>Searchable Wikis</h1><p>User-managed documentation for characters, preferences, memories, tools, and background knowledge.</p></div><button class="primary">New Wiki Page</button></div><div class="wikigrid"><article class="card pad"><h3>Kaien - Character Profile</h3><p class="muted">Trusted profile and approved memories.</p><span class="tag">agent</span></article><article class="card pad"><h3>Global User Preferences</h3><p class="muted">Personalization knowledge shared across agents.</p><span class="tag">global</span></article><article class="card pad"><h3>Evolution Rules</h3><p class="muted">How merge, split, and lineage events are recommended.</p><span class="tag">system</span></article></div>',
  energy: '<div class="title"><div><h1>Energy</h1><p>Energy makes computation visible. Orakai saves energy by consulting fewer agents and compressing context.</p></div></div><section class="card pad"><h2>Weekly Energy Usage</h2><div class="chart"><div class="bar" style="height:44%"></div><div class="bar" style="height:68%"></div><div class="bar" style="height:52%"></div><div class="bar" style="height:81%"></div><div class="bar" style="height:37%"></div></div></section>',
  settings: '<div class="title"><div><h1>Settings</h1><p>Control memory, background compilation, visibility, energy limits, and data export.</p></div></div><section class="card pad"><div class="settings"><div class="setting"><div><b>Background knowledge compilation</b><div class="muted">Allow Orakai to propose wiki updates from chats.</div></div><div class="toggle"></div></div><div class="setting"><div><b>Require approval for wiki edits</b><div class="muted">AI edits stay proposed until approved.</div></div><div class="toggle"></div></div></div></section>'
};
function go(id){document.getElementById('app').innerHTML=views[id];document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===id));document.getElementById('sidebar').classList.remove('open');location.hash=id;window.scrollTo(0,0)}
function init(){document.getElementById('nav').innerHTML=pages.map((id,i)=>'<button data-page="'+id+'" onclick="go(\''+id+'\')">'+icons[i]+' &nbsp; '+labels[i]+'</button>').join('');document.getElementById('bottomNav').innerHTML=pages.slice(0,5).map((id,i)=>'<button data-page="'+id+'" onclick="go(\''+id+'\')">'+icons[i]+'<span>'+labels[i]+'</span></button>').join('');document.getElementById('menu').onclick=()=>document.getElementById('sidebar').classList.toggle('open');go(views[location.hash.slice(1)]?location.hash.slice(1):'home')}
init();
